try this quickly

diff --git a/src/hooks/bin/post-refresh b/src/hooks/bin/post-refresh
--- a/src/hooks/bin/post-refresh
+++ b/src/hooks/bin/post-refresh
@@ -1,12 +1,11 @@
 #!/bin/bash -e
-# The post-refresh hook is similar to pre-refresh (above) in that it is called whenever the snap gets refreshed.
-# This hook is executed for the newly installed snap, before starting new services (if applicable).
-# This hook is a good place for any extra actions that need to be performed for the new revision of the snap.
-# It’s also a good place to test whether a refresh has succeeded, because if the test causes the hook to fail,
-# the refresh will be rolled-back and the original state of the snap restored.
+#? The post-refresh hook is similar to pre-refresh (above) in that it is called whenever the snap gets refreshed.
+#? This hook is executed for the newly installed snap, before starting new services (if applicable).
+#? This hook is a good place for any extra actions that need to be performed for the new revision of the snap.
+#? It’s also a good place to test whether a refresh has succeeded, because if the test causes the hook to fail,
+#? the refresh will be rolled-back and the original state of the snap restored.
 
 echo $SNAP
-echo $APP
 
 echo "$(snapctl services ${SNAP_NAME}.ocis-monitor)"
 
@@ -28,3 +27,11 @@ if snapctl is-connected ocis-config; then
     export OCIS_CONFIG_DIR="${SNAP}/configure"
     snapctl set-health okay
 fi
+
+if ! snapctl is-connected traefik-provider; then
+    echo >&2 "The traefik-provider interface is not connected."
+    snapctl set-health blocked "snap user: please connect the traefik-provider interface"
+    exit 1
+fi
+
+exec "$@"
diff --git a/src/hooks/utilities/configure-traefik-provider b/src/hooks/utilities/configure-traefik-provider
--- a/src/hooks/utilities/configure-traefik-provider
+++ b/src/hooks/utilities/configure-traefik-provider
@@ -1,35 +1,73 @@
 #!/bin/bash -e
 
 TRAEFIK_CHALLENGE_PROVIDER="$(snapctl get traefik.challenge-provider.provider)"
-# if [ -z "$TRAEFIK_CHALLENGE_PROVIDER" ]; then
 
-# fi
+install_traefik_provider() {
+    local fpath=${1}
+    if [ -f "${fpath}" ]; then
+        lookup_challenge_provider "${fpath}"
+        check_challenger_provider
+        echo "installing traefik provider with environment vars: ${fpath}"
+        # yq '(.. | select(tag == "!!str")) |= envsubst' "${fpath}" >"$SNAP/traefik-providers/providers/${fpath##*/}"
+        yq '(.. | select(tag == "!!str")) |= envsubst(nu,ne)' "${fpath}" >"$SNAP/traefik-providers/providers/${fpath##*/}"
+        # cp "${fpath}" /var/snap/traefik/common/acme.json
+    else
+        echo >&2 "installation failed: traefik provider file not found: ${fpath}"
+        snapctl set-health blocked "traefik provider file not found: ${fpath}"
+        exit 1
+    fi
+}
 
-case "${TRAEFIK_CHALLENGE_PROVIDER}" in
-"cloudflare")
-    # Environment Variable Name	Description
-    # CLOUDFLARE_HTTP_TIMEOUT	API request timeout
-    # CLOUDFLARE_POLLING_INTERVAL	Time between DNS propagation check
-    # CLOUDFLARE_PROPAGATION_TIMEOUT	Maximum waiting time for DNS propagation
-    # CLOUDFLARE_TTL	The TTL of the TXT record used for the DNS challenge
-    CF_API_EMAIL="$(snapctl get traefik.challenge-provider.cloudflare.email)"           #	Account email or CLOUDFLARE_EMAIL
-    CF_API_KEY="$(snapctl get traefik.challenge-provider.cloudflare.api-key)"           # or CLOUDFLARE_API_KEY, API key
-    CF_DNS_API_TOKEN="$(snapctl get traefik.challenge-provider.cloudflare.dns-token)"   #	or CLOUDFLARE_DNS_API_TOKEN, API token with DNS:Edit permission (since v3.1.0)
-    CF_ZONE_API_TOKEN="$(snapctl get traefik.challenge-provider.cloudflare.zone-token)" #	or CLOUDFLARE_ZONE_API_TOKEN, API token with Zone:Read permission (since v3.1.0)
-    PROVIDER="$(snapctl get traefik.challenge-provider.cloudflare)"
-    if [ -z "$PROVIDER" ]; then
-        echo >&2 "please set the following values: \
+lookup_challenge_provider() {
+    local fpath=${1}
+    if ! [ -f "${fpath}" ]; then
+        echo >&2 "traefik provider file not found: ${fpath}"
+        snapctl set-health blocked "traefik provider file not found: ${fpath}"
+        exit 1
+    else
+        TRAEFIK_CHALLENGE_PROVIDER="$(yq '.certificatesResolvers.*.acme.dnsChallenge.provider | envsubst(nu,ff)' "${fpath}")"
+        snapctl set traefik.challenge-provider.provider "${TRAEFIK_CHALLENGE_PROVIDER}"
+    fi
+}
+
+check_challenger_provider() {
+    case "${TRAEFIK_CHALLENGE_PROVIDER}" in
+    "cloudflare")
+        # Environment Variable Name	Description
+        # CLOUDFLARE_HTTP_TIMEOUT	API request timeout
+        # CLOUDFLARE_POLLING_INTERVAL	Time between DNS propagation check
+        # CLOUDFLARE_PROPAGATION_TIMEOUT	Maximum waiting time for DNS propagation
+        # CLOUDFLARE_TTL	The TTL of the TXT record used for the DNS challenge
+        CF_API_EMAIL="$(snapctl get traefik.challenge-provider.cloudflare.email)"           #	Account email or CLOUDFLARE_EMAIL
+        CF_API_KEY="$(snapctl get traefik.challenge-provider.cloudflare.api-key)"           # or CLOUDFLARE_API_KEY, API key
+        CF_DNS_API_TOKEN="$(snapctl get traefik.challenge-provider.cloudflare.dns-token)"   #	or CLOUDFLARE_DNS_API_TOKEN, API token with DNS:Edit permission (since v3.1.0)
+        CF_ZONE_API_TOKEN="$(snapctl get traefik.challenge-provider.cloudflare.zone-token)" #	or CLOUDFLARE_ZONE_API_TOKEN, API token with Zone:Read permission (since v3.1.0)
+        PROVIDER="$(snapctl get traefik.challenge-provider.cloudflare)"
+        if [ -z "$PROVIDER" ]; then
+            echo >&2 "please set the following values: \
         traefik.challenge-provider.cloudflare.email, \
         traefik.challenge-provider.cloudflare.api-key, \
         traefik.challenge-provider.cloudflare.dns-token \
         and traefik.challenge-provider.cloudflare.zone-token"
-        exit 1
-    fi
-    ;;
-*)
-    echo >&2 "Define the provider you plan to use \
+            exit 1
+        fi
+        ;;
+    "false")
+        snapctl set-health waiting "traefik.challenge-provider.provider not set"
+        ;;
+    *)
+        echo >&2 "Define the provider you plan to use \
     traefik.challenge-provider.<provider-name>, for more information
     see: (https://doc.traefik.io/traefik/https/acme/#providers)."
+        exit 1
+        ;;
+    esac
+}
+
+if ! snapctl is-connected traefik-provider; then
+    echo >&2 "The traefik-provider interface is not connected."
+    snapctl set-health blocked "snap user: please connect the traefik-provider interface"
     exit 1
-    ;;
-esac
+fi
+
+exec "$@"
